name: Practice testing

on:
  push:
    branches: [ main, practice ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-helloworld2:
    name: Testing 'helloworld2'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/helloworld2

  test-numeric:
    name: Testing 'numeric'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/numeric

  test-structures:
    name: Testing 'structures'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest practice/structures
